### ISSUE TITLE
v15 и ep9

### ISSUE THREAD

**Issue by XiMA4** [ErshovSergey/eset_mirror_script-docker-compose#1]
как можно добавить v15 и ep9?

**Comment by ErshovSergey** [comment]
База сигнатур получается с помощью 
https://github.com/Kingston-kms/eset_mirror_script
Спросите там.

**Comment by XiMA4** [comment]
> База сигнатур получается с помощью
> https://github.com/Kingston-kms/eset_mirror_script
> Спросите там.

там редактируется файл inc/init.php
а у вас я его не могу найти :(

**Comment by ErshovSergey** [comment]
В процессе сборки образа клонируется https://github.com/Kingston-kms/eset_mirror_script.git
Перезаписываются необходимые файлы - смотрите файл https://github.com/ErshovSergey/eset_mirror_script-docker-compose/blob/master/php/Dockerfile.
По аналогии можете добавить свою версию  inc/init.php.
